version: "0.1.{build}"
os: Visual Studio 2019
environment:
  My_TAG: "0.1.1"
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:My_TAG = $env:APPVEYOR_REPO_TAG_NAME
      }
      else
      {
        Update-AppveyorBuild -Version "0.1.$($env:APPVEYOR_BUILD_NUMBER)"
        $env:My_TAG = "0.1.$($env:APPVEYOR_BUILD_NUMBER)"
      }
before_build:
  - ps: nuget restore src\yTools.sln
build:
  project: src\yTools.sln
after_build:
  - 7z a yTools_%My_TAG%.zip %APPVEYOR_BUILD_FOLDER%\src\yTools\bin\Release
artifacts:
  - path: yTools_$(My_TAG).zip
    name: yTools_$(My_TAG)
deploy:
  release: $(My_TAG)
  description: yTools_$(My_TAG)
  provider: GitHub
  auth_token:
    secure: UcxrOFRJ1elSazvncT3nPGT+xt+CjplLJ/D0avU9+Qru7HBVxUfUdoe0Iwcd412S
  artifact: yTools_$(My_TAG).zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
